# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

#export ZSH_CUSTOM=$HOME/.zshrc.d

# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="muse"

# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# HIST_STAMPS="mm/dd/yyyy"
ZSH_CUSTOM=$HOME/.zshrc.d

# Look for plugins in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# plugins=(adb,bower,brew,brew-cask,cp,git,github,grunt,heroku,hub,nmap,node,npm,python,rsync,rvm,sublime,sudo,vagrant)

# User configuration

export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Developer/NVIDIA/CUDA-7.5/bin:`echo $HOME`/.rvm/bin"
# export MANPATH="/usr/local/man:$MANPATH"
export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-7.5/lib:$DYLD_LIBRARY_PATH

source $ZSH/oh-my-zsh.sh

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"
export COPYFILE_DISABLE=1

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/serginator/Downloads/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/serginator/Downloads/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/serginator/Downloads/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/serginator/Downloads/google-cloud-sdk/completion.zsh.inc'
fi

# Git mods
PATH="$PATH:$HOME/.git-mods"

# npm binaries
export PATH="$HOME/.npm-packages/bin:$PATH"

#GPG
export KEYID=0x5BA1DC635F07B886
export GPG_TTY=$(tty)
export PATH="/usr/local/sbin:$PATH"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export PATH="/Users/srs30/Library/Python/2.7/bin:$PATH"
export PATH="/Users/srs30/aps/bin:$PATH"

powerstat() {
    b=$(system_profiler SPPowerDataType)
    amp=$(echo "$b" | grep 'Amperage (mA):' | cut -d ':' -f 2 | xargs)
    volt=$(echo "$b" | grep 'Voltage (mV):' | cut -d ':' -f 2 | xargs)
    power=$(($amp * $volt / 1000))
    echo "$b" | grep --color=never -A 1 'Battery Information:'
    echo "$b" | grep --color=never -A 1 'Amperage (mA)'
    echo "      Total Power (mW): $power"
    echo ""
    echo "$b" | grep --color=never -A 99 'AC Charger Information:'
}

export PATH=$PATH:$HOME/.platformio/penv/bin

export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH

export PATH=$PATH:/Users/sergio.ruiz/Library/Python/3.9/bin

export PATH=$PATH:$HOME/.local/bin

# For using Fuzzy
source <(fzf --zsh)

# Android SDK
export ANDROID_SDK_ROOT=/Users/sergio.ruiz/Library/Android/sdk
export ANDROID_HOME=/Users/sergio.ruiz/Library/Android/sdk
export PATH=$PATH:/Users/sergio.ruiz/Library/Android/sdk/emulator:/Users/sergio.ruiz/Library/Android/sdk/platform-tools

export PATH="/opt/homebrew/opt/libxslt/bin:$PATH"

#Go Lang
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
export GOPRIVATE=github.com/taxfix/*

#act
export PATH=$PATH:/Users/sergio.ruiz/bin

if command -v ngrok &>/dev/null; then
  eval "$(ngrok completion)"
fi

if command -v llm &>/dev/null; then
  export OPENAI_API_KEY="$(llm keys get openai)"
fi

# export OPENAI_API_BASE='http://localhost:11667/v1' # or 'http://localhost:10000', depending on the tool
# export OPENAI_BASE_URL='http://localhost:12545/v1'
# export OPENAI_MODEL_NAME='phi3:latest'
# export DEFAULT_MODEL='phi3:latest'

if [ -f "/Users/sergio.ruiz/.config/fabric/fabric-bootstrap.inc" ]; then . "/Users/sergio.ruiz/.config/fabric/fabric-bootstrap.inc"; fi
export PATH="/opt/homebrew/opt/go@1.23/bin:$PATH"

# Added by Windsurf
export PATH="/Users/sergio.ruiz/.codeium/windsurf/bin:$PATH"

source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"

source $HOME/.zshrc.d/private.zsh


[[ "$TERM_PROGRAM" == "kiro" ]] && . "$(kiro --locate-shell-integration-path zsh)"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# ---- pyenv (load last; keep hooks alive) ----
export PYENV_ROOT="$HOME/.pyenv"
# Ensure shims are before everything else that might provide python
if [[ -d "$PYENV_ROOT" ]]; then
  export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"
fi

if command -v pyenv >/dev/null 2>&1; then
  # Use zsh-specific init so the hook is created
  eval "$(pyenv init - zsh)"
  eval "$(pyenv virtualenv-init -)"

  # Some tools (e.g. RVM/OMZ plugins) overwrite $chpwd_functions.
  # Re-append the pyenv hook if it's missing.
  typeset -ga chpwd_functions
  if (( $+functions[_pyenv_virtualenv_hook] )); then
    if [[ -z ${chpwd_functions[(r)_pyenv_virtualenv_hook]} ]]; then
      chpwd_functions+=(_pyenv_virtualenv_hook)
    fi
  fi
fi
# ---- end pyenv ----
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/sergio.ruiz/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
