# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

#export ZSH_CUSTOM=$HOME/.zshrc.d

# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="muse"

# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# HIST_STAMPS="mm/dd/yyyy"
ZSH_CUSTOM=$HOME/.zshrc.d

# Look for plugins in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(adb,bower,brew,brew-cask,cp,git,github,grunt,heroku,hub,nmap,node,npm,python,rsync,rvm,sublime,sudo,vagrant)

# User configuration

export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Developer/NVIDIA/CUDA-7.5/bin:`echo $HOME`/.rvm/bin"
# export MANPATH="/usr/local/man:$MANPATH"
export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-7.5/lib:$DYLD_LIBRARY_PATH

source $ZSH/oh-my-zsh.sh

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"
export COPYFILE_DISABLE=1

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/serginator/Downloads/google-cloud-sdk/path.zsh.inc ]; then
  source '/Users/serginator/Downloads/google-cloud-sdk/path.zsh.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/serginator/Downloads/google-cloud-sdk/completion.zsh.inc ]; then
  source '/Users/serginator/Downloads/google-cloud-sdk/completion.zsh.inc'
fi

# Git mods
PATH="$PATH:$HOME/.git-mods"

# npm binaries
export PATH="$HOME/.npm-packages/bin:$PATH"

#GPG
export KEYID=0x5BA1DC635F07B886
export GPG_TTY=$(tty)
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
export PATH="/Users/srs30/Library/Python/2.7/bin:$PATH"
export PATH="/Users/srs30/aps/bin:$PATH"

powerstat() {
    b=$(system_profiler SPPowerDataType)
    amp=$(echo "$b" | grep 'Amperage (mA):' | cut -d ':' -f 2 | xargs)
    volt=$(echo "$b" | grep 'Voltage (mV):' | cut -d ':' -f 2 | xargs)
    power=$(($amp * $volt / 1000))
    echo "$b" | grep --color=never -A 1 'Battery Information:'
    echo "$b" | grep --color=never -A 1 'Amperage (mA)'
    echo "      Total Power (mW): $power"
    echo ""
    echo "$b" | grep --color=never -A 99 'AC Charger Information:'
}
